---
name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  PY_VER: '3.7'
  IMG_VARIANT: '-slim'

# Do not depend on platform enviroment
# https://hynek.me/articles/simple-python-azure-pipelines/
# Also more easily repoducable on local machine
stages:

- stage: 'Tox'
  jobs:
  - template: .ci/azure-job-python-tox.yml
    parameters:
      name: 'Env'
      toxenvs:
        Lint: lint
        Style: style
        Package: pkg
  - template: .ci/azure-job-python-tox.yml
    parameters:
      name: 'PyTest'
      pytest: True
      toxenvs:
        3.5: py35
        3.6: py36
        3.7: py37

- stage: 'Publish'
  jobs:
  - job: 'Package'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo 'TODO - python setup wheel && twine'