# pool:
#   vmImage: 'ubuntu-16.04

resources:
  containers:
  - container: py37
    image: python:3.7-slim

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      lint:
        containerResource: py37
        toxenv: lint
      pytest:
        containerResource: py37
        toxenv: py37

  container: $[ variables['containerResource'] ]

  steps:
  - script: pip install tox
  - script: tox -e $[ variables['toxenv'] ]

# pool:
#   vmImage: 'ubuntu-16.04'
# container: ubuntu:16.04
# steps:
# - script: printenv