---
parameters:
  name: null
  vmImage: 'ubuntu-16.04'
  vars: {}
  pytest: False
  toxargs: '--skip-missing-interpreters'
  toxenvs: {}

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables: ${{ parameters.vars }}
  strategy:
    matrix:
      ${{ each toxenv in parameters.toxenvs }}:
        ${{ toxenv.key }}:
          TOXENV: ${{ toxenv.value }}
          ${{ if eq(parameters.pytest, True) }}:
            PY_VER: ${{ toxenv.key }}

  steps:
  - script: 'docker-compose --file tests/docker-compose.yml build'
    displayName: 'Build container'
    env:
      TOX_PARALLEL_NO_SPINNER: 1
  - script: 'docker-compose --file tests/docker-compose.yml run tox ${{ parameters.toxargs }} --'
    displayName: 'Run Tox'
  - task: PublishTestResults@2
    condition: ${{ parameters.pytest }}
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  - task: PublishCodeCoverageResults@1
    condition: ${{ parameters.pytest }}
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
      failIfCoverageEmpty: True