---
parameters:
  name: null
  vmImage: 'ubuntu-16.04'
  pytest: False
  toxargs: ''
  toxenvs: {}

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ each toxenv in parameters.toxenvs }}:
        ${{ toxenv.key }}:
          TOXENV: ${{ toxenv.value }}
          ${{ if eq(parameters.pytest, 'true') }}:
            PY_VER: ${{ toxenv.key }}

  steps:
  - script: 'docker-compose --file tests/docker-compose.yml build'
    displayName: 'Build container'
  - script: 'docker-compose --file tests/docker-compose.yml run tox ${{ parameters.toxargs }}'
    displayName: 'Run Tox'

  - task: PublishTestResults@2
    condition: ${{ parameters.pytest }}
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'